[package]
name = "chain-ethereum"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
alloy = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
wallet-domain = { path = "../wallet-domain" }
chain-core = { path = "../chain-core" }
keystore = { path = "../keystore" }
rpc-client = { path = "../rpc-client" }
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
