[package]
name = "chain-bitcoin"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
bdk_wallet = { workspace = true }
bdk_esplora = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
wallet-domain = { path = "../wallet-domain" }
chain-core = { path = "../chain-core" }
keystore = { path = "../keystore" }
secure-storage = { path = "../secure-storage" }
rpc-client = { path = "../rpc-client" }
chrono = { workspace = true }
uuid = { workspace = true }
bech32 = { workspace = true }
