[package]
name = "chain-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
wallet-domain = { path = "../wallet-domain" }
chrono = { workspace = true }